### ISSUE TITLE
Enhancement: Previews/markers to cover/presentation gif/s

### ISSUE THREAD

**Issue by bunkmate5127** [bdbenim/stash-empornium#100] opened 2023-10-30 12:23 UTC
I don't know much about how folk get their really long run-time ultra-compressed gifs that don't look like garbage. But assuming this conversion is relatively straight forward and uses foss that can be included in the docker image (rather than another web api or something—though I suppose that would also be feasible), then:

### "Easy"
Stash already generates a generic preview .mp4 video that's 10 seconds long, this seems like a convenient source for automatic conversion to a cover.gif. Unfortunately they sample from the very start of the video, so often the leading frames in these previews are garbage. 

### Less easy
Alternatively/in addition, and more challenging from a development point of view, markers conveniently generate a series of little .mp4s that are 20 seconds long. You could envision a few options here:
- Dumping of each of these markers into their own .gif in the presentation along with their marker title. These might need shortening to 5 or 10 seconds each.
- Stitching all the markers together to form a manual preview gif (but that actually includes the "best bits" rather than a random sampling). The compilation of markers would probably only use the first 2 or 3 seconds from each marker.

The use of markers auto-generated .mp4s might be a red herring given their length and the likely need to sub-sample them anyway. It might actually be better/easier to run ffmpeg on the scene's file directly using only the markers time-points.

**Comment by bunkmate5127** [comment] 2023-10-30 12:33
Jerking doesn't yet support webp, the Emp devs have made mutterings about adding it. I believe the upstream imagehosting software (chevereto) now supports animated webp, but jerking is heavily customised so updating their core to reflect the mainline chevereto is not particularly straight forward. As such, I don't think support for webp on Emp is forthcoming anytime soon—but the devs might prioritise it with enough prodding.

That said, webp is actually an outdated format now (2010). The internet will move toward a new paradigm in jxl (jpeg xl) in the near future. JXL is both backward compatible with jpg, supports _everything_, is open, as is hugely performant in every metric. But JXL is so new that even the browsers haven't added support in their mainline releases yet. So this is not something that needs much consideration at this point in time.

**Comment by bdbenim** [comment] 2023-10-30 16:13
Thanks for the suggestion! I actually got halfway through implementing the "easy" version a while ago before getting distracted by other issues, and I hadn't thought of using markers in the ways you mention. I'll have to take another look at adding animated gifs based on these ideas. Hopefully support for better formats comes soon.

**Comment by bdbenim** [comment] 2023-11-16 03:04
@bunkmate5127 I just noticed something from your original comment:

> Unfortunately they sample from the very start of the video, so often the leading frames in these previews are garbage.

This is actually configurable from Stash Settings->System->Preview Generation Options. I have mine set to skip the first and last 2% which is enough to skip the boilerplate intros for most studios, but you might want to skip more from the beginning.

![image](https://github.com/bdbenim/stash-empornium/assets/97994155/451b08c4-b535-4477-91a6-8c054454710f)

**Comment by bdbenim** [comment] 2023-11-16 05:05
Closing for now, but so far it's just the main scene preview that's used. I'm still planning to implement something with marker previews though

**Comment by bunkmate5127** [comment] 2023-11-19 23:40
Wow excellent, I didn't know about that option in stash... now I'll have to set it and regenerate 25,000 scene previews...

I tried to play with this today on 0.16.1 (docker), my config has automatically inherited these lines (I used the new webui to set them to true—the webui is fantastic btw):

```
# Option imported automatically:
use_preview = true
# Option imported automatically:
animated_cover = true
```

However, my uploads still use the default cover image instead of the gif. My reading of these options would lead me to believe this is not an issue with needing to manually change template or anything of that nature (indeed the cover image should be entirely independent of the template anyway).

**Comment by bdbenim** [comment] 2023-11-20 00:31
That's correct, you should not need to change the template. Just to be clear though, this option sets the **upload** cover (what shows up at the top right of a torrent's page, or when hovering over an its title), not the **template** cover (what's displayed within the presentation). I set it up that way because it's how I've seen uploaders typically do it - an animated (low-res due to file size limits) preview on the upload itself, but a static (high-res) image within the presentation. If you want the animated preview inside the presentation itself, then you just need to replace `{{ cover }}` with `{{ preview }}` in the template.

**Comment by bunkmate5127** [comment] 2023-11-20 00:41
Yeah, I understand the difference—and think that your intended implementation of this is _ideal_ (and conventional).

The cover (as in separate from the template) is still the static cover image with these options set (for extra clarity, the static cover image appears in both places).

To be clear, here are my (webui) settings:
![Screenshot 2023-11-20 at 13-35-14 Settings - stash-empornium](https://github.com/bdbenim/stash-empornium/assets/149383997/28ef6d42-9b27-4009-8c93-717fa0c66f09)

With these settings generating a scene results in this cover image (note the .jpg extension):
![Screenshot 2023-11-20 at 13-35-53 Upload Empornium](https://github.com/bdbenim/stash-empornium/assets/149383997/82a9b13e-7b32-43bb-84c6-0630a276ef5d)

I don't understand the function of "Move method".

**Comment by bdbenim** [comment] 2023-11-20 00:55
Hmm that's strange. Can you confirm that scene has a preview generated in stash? It should be located at {stash-url}/scene/{scene-id}/preview. I'm guessing it's a bug in the code, but just in case.

And yeah, "Move Method" doesn't have much documentation yet. It only applies if you're including a scene's gallery in the torrent (and in the future for scene packs as well). Since all the files need to be together in the same directory in order to generate and seed the torrent, the backend has to move the scene and gallery into a new directory together. That directory is specified in the `Media Directory` field, and the way the files are moved to that directory is either by copying them (default), soft/symlinking, or hard linking. Copying the files is the most reliable method, but uses a lot of extra space. Soft and hard links are basically two different ways of just creating shortcuts to the files, which saves a lot of space, but they won't work in all situations, especially when docker is involved. But if you're just uploading a scene without the gallery, these options won't get used at all because the files won't need to be moved.

I'm slowly adding tooltips to the settings options, and at some point I plan to add a help button as well to explain some of these options.

**Comment by bunkmate5127** [comment] 2023-11-20 01:35
The previews definitely exist (and function within stash itself), I've tried with multiple scenes. The url you've mentioned works in linking to the previews. The relevant .mp4 files are all located on the stash server under {stash storage path}/generated/screenshots I wonder why they've chosen to use the term screenshots for this... probably historic.

Interestingly {stash-url}/scene**s**/{scene-id}/preview just links to the scene itself, this is a weird convention to split the generated stuff from the scene by use of/lack of the plural in the url—this is of course of no relevance to this project.

**Re "Move Method"**: I see, yes that makes sense with the move method. I was scratching my brain and coming up blank with why anything would need to be moved—but it makes sense in the context of including images with the video. I'd overlooked that that option had been added and what the repercussions would be.

**Re Tooltips**: sounds fantastic.

**Comment by bdbenim** [comment] 2023-11-20 03:13
I'm going to push an update here in a minute that adds a bit of extra debug output to help figure out what's going wrong. In the meantime, I just discovered that I accidentally left a line of code in from my own debugging. Instead of saving the preview in a temp folder, it actually saves it in the same directory as your config file. Do you have a file called `preview.gif` in your config directory? If so, is it a proper animated gif or is it maybe corrupted in some way?

**Comment by bdbenim** [comment] 2023-11-20 03:35
Actually, I might know the problem. Can you restart the server and try again?

**Closed** 2023-11-20 03:44 UTC
Labels: enhancement

**Comment by bunkmate5127** [comment] 2023-11-20 03:52
I don't have a preview.gif in the cover directory. But I see you've got 0.16.2 up, so I'll give that a whirl and report back.

**Comment by bdbenim** [comment] 2023-11-20 03:55
Sounds good! It's not fixed yet in 0.16.2, but if I'm right about what the problem is then it should start working for you anyway. It seems that the change of setting was ignored until the server gets restarted. It'll be patched in 0.16.3 here soon

**Comment by bunkmate5127** [comment] 2023-11-20 04:03
Ah that would make sense. 

I don't recall restarting the server after changing it. I usually do it routinely through lack of trust, but everything appeared to keep functioning finally—I shall go back to my default state of not trusting things XD.

The debug log now shows "2023-11-20 03:59:21,058 - INFO - Getting scene preview" this doesn't have an associated uploading info line, but it appears to have uploaded all the same.

...I committed the fatal sin of not turning it off and on again before asking for help, sorry for the trouble. I would usually do this when altering the config.toml manually (i.e. stop it, alter, start it) but this for whatever reason didn't even occur to me with the new webui.

**Comment by bdbenim** [comment] 2023-11-20 04:06
No trouble! You helped me find a bug that otherwise would have likely remained hidden for a while. One benefit of the webui is that in theory you shouldn't have to restart anything after changing settings (with maybe some rare exceptions), and thanks to this I'm realizing that there are at least a few other settings that have this exact problem. I'm now going through and tidying those up so they hopefully won't cause any issues in the future.
